# Generated by Django 6.1 on 2026-08-13 13:35

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient_address',
            field=models.CharField(default='', max_length=255, verbose_name='Адрес получателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Эл. почта получателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_first_name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя получателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_last_name',
            field=models.CharField(default='', max_length=255, verbose_name='Фамилия получателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_mid_name',
            field=models.CharField(default='', max_length=255, verbose_name='Отчество получателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region='RU', verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('delivered', 'Доставлен'), ('delivery', 'В доставке'), ('canceled', 'Отменен')], default='pending', max_length=20),
        ),
    ]
