# Generated by Django 6.1 on 2026-08-09 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_remove_user_name_user_midname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='midname',
            new_name='mid_name',
        ),
    ]
