# Generated by Django 6.1 on 2026-08-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_midname_user_mid_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramprofile',
            name='tg_fullname',
            field=models.CharField(default='', max_length=255, verbose_name='Имя пользователя TG'),
        ),
        migrations.AlterField(
            model_name='telegramprofile',
            name='tg_username',
            field=models.CharField(max_length=255, verbose_name='Юзернейм TG'),
        ),
    ]
