# Generated by Django 6.1 on 2026-08-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_telegramprofile_tg_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramprofile',
            name='tg_uid',
            field=models.CharField(max_length=255, unique=True, verbose_name='TG ID'),
        ),
    ]
