# Generated by Django 6.1 on 2026-08-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_recipient_address_order_recipient_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='recipient_mid_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Отчество получателя'),
        ),
    ]
