# Generated by Django 6.1 on 2026-08-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Введите акутальный токен бота от @BotFather', max_length=255, verbose_name='Telegram Токен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Бот активен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Основные',
            },
        ),
    ]
